version: "3.9"
services:
  symfony:
    restart: unless-stopped
    stop_grace_period: 3s
    build:
      context: .
      dockerfile: "dev.dockerfile"
      target: symfony
    env_file: .env
    environment:
      DATABASE_URL: "postgresql://${PSQL_USER}:${PSQL_PASSWORD}@db:5432/${PSQL_DATABASE}?serverVersion=15&charset=utf8"
      AP_DOMAIN: ${AP_DOMAIN}
    expose:
      - 8087
    ports:
      - 8087:8087
    networks:
      - frontend
      - backend
    volumes:
      - .:/app
  db:
    restart: unless-stopped
    stop_grace_period: 3s
    image: "postgres:15"
    env_file: .env
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
    expose:
      - 5432
    ports:
      - 8001:5432
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_DB: ${PSQL_DATABASE}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
    internal: true

volumes:
  postgresql:
